Repository ut-issl/s2e-user-for-c2a-core, pull requests merged in 2023-04, with the labels that each got.

#27 Update for s2e-core v6.0.0
  .github/workflows/build.yml
  .github/workflows/check-format.yml
  CMakeLists.txt
  data/ini/c2a_core_disturbance.ini
  data/ini/c2a_core_local_environment.ini
  data/ini/c2a_core_sample_sat.ini
  data/ini/c2a_core_sim_base.ini
  data/ini/c2a_core_structure.ini
  src/Simulation/Case/c2a_core_sample_case.cpp
  src/Simulation/Case/c2a_core_sample_case.h
  src/Simulation/Spacecraft/c2a_core_sample_components.cpp
  src/Simulation/Spacecraft/c2a_core_sample_components.h
  src/Simulation/Spacecraft/c2a_core_sample_sat.cpp
  src/Simulation/Spacecraft/c2a_core_sample_sat.h
  src/s2e_for_c2a_core.cpp
Labels: priority::high

#29 README の S2E core バージョンを v6.0.0 に
  README.md
Labels: documentation, priority::high

#30 Update main (v2.0.0) on 2023-04-09: S2E Core v6.0.0 対応版
  .github/workflows/build.yml
  .github/workflows/check-format.yml
  .github/workflows/labeler.yml
  CMakeLists.txt
  README.md
  data/ini/c2a_core_disturbance.ini
  data/ini/c2a_core_local_environment.ini
  data/ini/c2a_core_sample_sat.ini
  data/ini/c2a_core_sim_base.ini
  data/ini/c2a_core_structure.ini
  data/initialize_files/c2a_core_disturbance.ini
  data/initialize_files/c2a_core_local_environment.ini
  data/initialize_files/c2a_core_sample_sat.ini
  data/initialize_files/c2a_core_sim_base.ini
  data/initialize_files/c2a_core_structure.ini
  data/initialize_files/components/.gitkeep
  data/initialize_files/scenario/.gitkeep
  src/Simulation/Case/c2a_core_sample_case.cpp
  src/Simulation/Case/c2a_core_sample_case.h
  src/Simulation/Spacecraft/c2a_core_sample_components.cpp
  src/Simulation/Spacecraft/c2a_core_sample_components.h
  src/Simulation/Spacecraft/c2a_core_sample_sat.cpp
  src/Simulation/Spacecraft/c2a_core_sample_sat.h
  src/components/.gitkeep
  src/s2e_for_c2a_core.cpp
  src/simulation/case/c2a_core_sample_case.cpp
  src/simulation/case/c2a_core_sample_case.hpp
  src/simulation/ground_station/.gitkeep
  src/simulation/spacecraft/c2a_core_sample_components.cpp
  src/simulation/spacecraft/c2a_core_sample_components.hpp
  src/simulation/spacecraft/c2a_core_sample_satellite.cpp
  src/simulation/spacecraft/c2a_core_sample_satellite.hpp
Labels: enhancement, priority::high, C2A
